// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ttwxwkkjnxwjwyfxpubn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR0d3h3a2tqbnh3and5ZnhwdWJuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1MDU2NTgsImV4cCI6MjA3MTA4MTY1OH0.YkHWU7GjmovIp356AfoXTml3S0TLuSW2Y2Rsdu2iCl0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});